[workspace]
members = [
    "crates/gunbatte-core",
    "crates/gunbatte-node",
    "crates/gunbatte-lobby",
    "crates/gunbatte-gameserver",
    "crates/gunbatte-server",
    "crates/gunbatte-runner",
    "crates/gunbatte-wasm",
    "crates/gunbatte-bot-client",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ahaqqu/gunbatte"

[profile.release]
opt-level = 3
lto = "thin"
